"""
Django settings for llm_project project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--&p0z-v0t1g^-g1qbo#+x7u-da6#_i-b=k%$40x19e4)0v^yh&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.31.58','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'llm_app',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'llm_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'llm_project.wsgi.application'

HAS_WEAVAITEDB = True


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SYSTEM_PROMPTS = {
    'Default_Personal': "You are an AI assistant.Answer user's question,make response to them.If you really need Use these tools whenever possible to answer user queries . ",
    'error_message': "Sorry, I couldn't process that. Please try again.",
    'default_prompt': "Please provide your input.",
}

USER_DATA_FILE = 'llm_project/llm_app/users.json'
MODEL_TYPE='api'
MODEL_PATH = 'llm_project/llm_app/models/model.gguf'
MODEL_CHAT_FORMAT = 'gemma'
MODEL_ID='meta-llama/Llama-3.1-8B-Instruct'
MODEL_API_URL = 'http://localhost:8080'  # URL for the llama.cpp API

AI_TEXT_PATH='ai_txt/'

LOGIN_URL = '/login/'

AUTHENTICATION_BACKENDS = [
    'llm_app.auth_backend.JsonFileBackend',  # Path to your custom backend
    'django.contrib.auth.backends.ModelBackend',  # Default Django backend (if needed)
]

# Use in-memory sessions (not persistent)
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

# Use Django's default local memory cache for session storage
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

GEN_TEMPERATURE = 1

GEN_REPEAT_PENALTY = 1.5

GEN_MAX_TOKEN = 4096

OPEN_AI_KEY = ""

LANGSMITH_TRACING="false"

LANGSMITH_ENDPOINT="https://api.smith.langchain.com"

LANGSMITH_API_KEY=""

LANGSMITH_PROJECT=""
